### ISSUE TITLE
Cannot import name UserList

### ISSUE THREAD

**Issue by tinoloni** [cjaymes/pyscap#1]
Cloned git (24th June 2017).

```
(python) dev@ubuntu:~/pyscap$ ls
agent        inventory_sample.ini    pytest.ini        scap
clean.sh     LICENSE                 python            setup.py
COPYING      namespace_registry.py   README.md         stub_from_xsd.py
fixtures     namespace_registry.pyc  requirements.txt  test
__init__.py  pyscap.py               sample_content    TODO.txt
```
Installed modules from requirements without issues.

```
(python) dev@ubuntu:~/pyscap$ pip install -r requirements.txt 
Collecting appdirs==1.4.3 (from -r requirements.txt (line 1))
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting asn1crypto==0.22.0 (from -r requirements.txt (line 2))
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting cffi==1.7.0 (from -r requirements.txt (line 3))
  Using cached cffi-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting colorama==0.3.9 (from -r requirements.txt (line 4))
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting cryptography==1.8.1 (from -r requirements.txt (line 5))
Collecting idna==2.1 (from -r requirements.txt (line 6))
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting ipaddress==1.0.18 (from -r requirements.txt (line 7))
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting ntlm-auth==1.0.3 (from -r requirements.txt (line 8))
  Using cached ntlm_auth-1.0.3-py2.py3-none-any.whl
Collecting packaging==16.8 (from -r requirements.txt (line 9))
  Using cached packaging-16.8-py2.py3-none-any.whl
Collecting paramiko==2.1.2 (from -r requirements.txt (line 10))
  Using cached paramiko-2.1.2-py2.py3-none-any.whl
Collecting py==1.4.33 (from -r requirements.txt (line 11))
  Using cached py-1.4.33-py2.py3-none-any.whl
Collecting pyasn1==0.1.9 (from -r requirements.txt (line 12))
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pycparser==2.14 (from -r requirements.txt (line 13))
Collecting pyparsing==2.2.0 (from -r requirements.txt (line 14))
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pytest==3.0.7 (from -r requirements.txt (line 15))
  Using cached pytest-3.0.7-py2.py3-none-any.whl
Collecting pywinrm==0.2.2 (from -r requirements.txt (line 16))
  Using cached pywinrm-0.2.2-py2.py3-none-any.whl
Collecting requests==2.13.0 (from -r requirements.txt (line 17))
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting requests-kerberos==0.11.0 (from -r requirements.txt (line 18))
  Using cached requests_kerberos-0.11.0-py2.py3-none-any.whl
Collecting requests-ntlm==1.0.0 (from -r requirements.txt (line 19))
  Using cached requests_ntlm-1.0.0-py2.py3-none-any.whl
Collecting six==1.10.0 (from -r requirements.txt (line 20))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting xmltodict==0.11.0 (from -r requirements.txt (line 21))
  Using cached xmltodict-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=11.3 in ./python/lib/python2.7/site-packages (from cryptography==1.8.1->-r requirements.txt (line 5))
Collecting enum34 (from cryptography==1.8.1->-r requirements.txt (line 5))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pykerberos<2.0.0,>=1.1.8; sys_platform != "win32" (from requests-kerberos==0.11.0->-r requirements.txt (line 18))
Installing collected packages: appdirs, asn1crypto, pycparser, cffi, colorama, ipaddress, six, idna, enum34, pyparsing, packaging, cryptography, ntlm-auth, pyasn1, paramiko, py, pytest, xmltodict, requests, requests-ntlm, pywinrm, pykerberos, requests-kerberos
Successfully installed appdirs-1.4.3 asn1crypto-0.22.0 cffi-1.7.0 colorama-0.3.9 cryptography-1.8.1 enum34-1.1.6 idna-2.1 ipaddress-1.0.18 ntlm-auth-1.0.3 packaging-16.8 paramiko-2.1.2 py-1.4.33 pyasn1-0.1.9 pycparser-2.14 pykerberos-1.1.14 pyparsing-2.2.0 pytest-3.0.7 pywinrm-0.2.2 requests-2.13.0 requests-kerberos-0.11.0 requests-ntlm-1.0.0 six-1.10.0 xmltodict-0.11.0
```

Then tried to execute setup.py as follows:
```
(python) dev@ubuntu:~/pyscap$ python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
running build
running build_py
file scap.py (for module scap) not found
file scap.py (for module scap) not found
running install_lib
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

running install_egg_info
Writing /home/dev/pyscap/python/lib/python2.7/site-packages/PySCAP-0.1-py2.7.egg-info
```
```
(python) dev@ubuntu:~/pyscap$ python pyscap.py -h
Traceback (most recent call last):
  File "pyscap.py", line 33, in <module>
    import namespace_registry
  File "/home/dev/pyscap/namespace_registry.py", line 20, in <module>
    from scap.Model import Model
  File "/home/dev/pyscap/scap/Model.py", line 18, in <module>
    from collections import UserList, UserDict
ImportError: cannot import name UserList
```

**Comment by cjaymes** [comment]
Looks like you're running python 2.7...I'm coding based on 3.5.

**Comment by tinoloni** [comment]
That's right. 

I still needed to remove line 38 in pyscap.py (unknown module). 

```
python3 pyscap.py 
2017-06-26 18:58:29,637 - __main__ - DEBUG - Start: Mon Jun 26 18:58:29 2017
usage: pyscap.py [-h] [--version] [--verbose] [--output [OUTPUT]]
                 [--inventory INVENTORY [INVENTORY ...]]
                 [--host HOST [HOST ...]]
                 [--collect | --benchmark | --list-hosts | --parse PARSE [PARSE ...]]
pyscap.py: error: No valid operation was given
```

A usage and feature description would be great.
