### ISSUE TITLE
How can I implement Host discovery on host system

### ISSUE THREAD

**Issue by tinoloni** [cjaymes/pyscap#2]
```
python3 pyscap.py --host 192.168.178.75 --collect
```

Successfully connected via SSHCollector.

```
Traceback (most recent call last):
  File "pyscap.py", line 151, in <module>
    collector.collect()
  File "/home/finn/pyscap/scap/collector/SSHCollector.py", line 42, in collect
    raise NotImplementedError('Host discovery has not been implemented for host: ' + self.host.hostname)
NotImplementedError: Host discovery has not been implemented for host: 192.168.178.75
2017-06-26 19:03:20,806 - __main__ - DEBUG - End: Mon Jun 26 19:03:20 2017
```

Maybe you can find a moment to write a little documentation.

**Comment by cjaymes** [comment]
Honestly, the project is barely in alpha stage yet. There's a bazillion scap standards to parse, so I had been focusing on that till fairly recently. I'm currently working on the OVAL collection process, so once I get some of that done, there will actually be something it can collect versus just connecting & figuring out what kind of system it's connected to.

I've been testing everything using localhost for now and mostly using pytest instead of running the program. So the components work, but they aren't all tied together into the script yet.

Would you be willing to test some things for me when I get them put together? How much development experience do you have (pytest for instance)?

**Comment by tinoloni** [comment]
That would be great. I'm developing a few things in python for my company. Especially a NIST standardized vulnerability assesment since 1 year.  The thing I didn't really figured out yet is to integrate this OVAL collection process into it.  So I would be glad if I can help you. 

If I find time for it, i will try it.

**Comment by cjaymes** [comment]
The main script should be working better now. Try out --detect to run the basic collectors. I'm going to use --collect for oval system characteristics, so that isn't quite ready yet.
