### ISSUE TITLE
Could not parse system uuid from dmidecode

### ISSUE THREAD

**Issue by tinoloni** [cjaymes/pyscap#8]
```
(venv) dev@ubuntu:~/pyscap$ python3 pyscap.py --detect --host localhost --verbose -v
2017-07-12 21:48:02,706 - __main__ - DEBUG - Set console logging level to DEBUG
2017-07-12 21:48:02,706 - __main__ - INFO - Detect operation
2017-07-12 21:48:02,706 - __main__ - DEBUG - Argument: benchmark = False
2017-07-12 21:48:02,706 - __main__ - DEBUG - Argument: verbose = 2
2017-07-12 21:48:02,706 - __main__ - DEBUG - Argument: list_hosts = False
2017-07-12 21:48:02,706 - __main__ - DEBUG - Argument: detect = True
2017-07-12 21:48:02,706 - __main__ - DEBUG - Argument: parse = None
2017-07-12 21:48:02,707 - __main__ - DEBUG - Argument: inventory = None
2017-07-12 21:48:02,707 - __main__ - DEBUG - Argument: output = -
2017-07-12 21:48:02,707 - __main__ - DEBUG - Argument: host = ['localhost']
2017-07-12 21:48:02,707 - __main__ - DEBUG - Argument: collect = False
2017-07-12 21:48:02,707 - __main__ - ERROR - Could not read from inventory file /home/dev/.pyscap/inventory.ini
Sudo password for host localhost: 
Traceback (most recent call last):
  File "/home/dev/pyscap/scap/collector/linux/UniqueIdCollector.py", line 29, in collect
    DmiDecodeCollector(self.host, {}).collect()
  File "/home/dev/pyscap/scap/collector/linux/DmiDecodeCollector.py", line 38, in collect
    raise RuntimeError('Could not parse system uuid from dmidecode')
RuntimeError: Could not parse system uuid from dmidecode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyscap.py", line 186, in <module>
    col.collect()
  File "/home/dev/pyscap/scap/collector/linux/UniqueIdCollector.py", line 33, in collect
    RootFsUuidCollector(self.host, {}).collect()
  File "/home/dev/pyscap/scap/collector/linux/RootFsUuidCollector.py", line 26, in collect
    self.host.facts['root_uuid'] = out_lines[0]
IndexError: list index out of range
2017-07-12 21:48:24,920 - __main__ - DEBUG - End: Wed Jul 12 21:48:24 2017
```

**Comment by cjaymes** [comment]
3ec787c should fix it. pulling directly from /sys
